name: Official Repo Build vyos ISO circinus

on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * 3
    
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set VyOS Version
      run: |
        echo "VYOS_VERSION=circinus-$(date -u +%Y%m%d%H%M)" >> $GITHUB_ENV

    - name: Pull vyos-build Docker Image
      run: |
        docker pull vyos/vyos-build:circinus
        
    - name: Build iso
      run: |
        git clone -b circinus --single-branch https://github.com/vyos/vyos-build
        cd vyos-build
        echo "SHA_COMMIT=$(git log -1 --format=%H)" >> $GITHUB_ENV
        docker run --rm --privileged -v $(pwd):/vyos -w /vyos vyos/vyos-build:circinus bash -c 'sudo ./build-vyos-image generic --architecture amd64 --build-type release --version "${{ env.VYOS_VERSION }}"'
        cd ..
        echo "HASH=$(sha256sum vyos-build/build/vyos-${{ env.VYOS_VERSION }}-generic-amd64.iso | awk '{print $1}')" >> $GITHUB_ENV

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: vyos-build/build/vyos-${{ env.VYOS_VERSION }}-generic-amd64.iso
        tag: vyos-${{ env.VYOS_VERSION }}-${{ env.SHA_COMMIT }}-${{ env.HASH }}
        overwrite: true
